*** Settings ***
Documentation     打开网页的地址

*** Variables ***
${login}          http://211.87.224.235:8800/loginpage.php    # 登录界面
${submit}         http://211.87.224.235:8800/submitpage.php    # 提交页面前缀
${modify_info}    http://211.87.224.235:8800/modifypage.php    # 更改注册信息页面
${rank}           http://211.87.224.235:8800/ranklist.php    # 排名页面
${status}         http://211.87.224.235:8800/status.php    # 状态页面
${index}          http://211.87.224.235:8800/    # 主页页面
${register}       http://211.87.224.235:8800/registerpage.php    # 注册界面
${problemset}     http://211.87.224.235:8800/problemset.php    # 问题集界面
